[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "camera 'none'; display-capture 'none'; document-domain 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google-analytics.com 'unsafe-inline'; style-src 'self'; img-src data: 'self' www.google-analytics.com https://www.netlify.com"

    

